<h1>Posts</h1>

<?php $this->mensagem(); ?>

<p>[<a href="<?php echo $this->url(array('action' => 'create')); ?>">novo</a>]</p>

<table border="1">
  <thead>
    <tr>
      <td>#</td>
      <td>Categoria</td>
      <td>Titulo</td>
      <td></td>
    </tr>
  </thead>
  <tbody>
      <?php foreach ($this->posts as $post) { ?>
        <tr>
          <td><?php echo $post['idpost']; ?></td>
          <td><?php echo $post['categoria']; ?></td>
          <td><?php echo $post['titulo']; ?></td>
          <td>
            [<a href="<?php echo $this->url(array('action' => 'update', 'idpost' => $post['idpost'])); ?>">editar</a>]
            <?php if ($this->podeApagar) { ?>[<a href="<?php echo $this->url(array('action' => 'delete', 'idpost' => $post['idpost'])); ?>">apagar</a>]<?php } ?>
          </td>
        </tr>
    <?php } ?>
  </tbody>
</table>
